name: 'Save logs to json action'
description: 'Save logs to json file'

inputs:
  json:
    description: 'json to data to add in files'
    required: true
    default: '{}'

outputs:
  json:
    description: | 
      'Save log data structure
        {
          status: string;
          environment: string;
          repository: string;
          runBy: string;
          packageName: string;
          latestCommitHash: string;
          commitLogs: [
            {
              commit: string;
              author: string;
              message: string;
              url: string;
            }
          ];
        }
      '
  json-string:
    description: 'Data from json file in string form'

runs:
  using: node20
  main: dist/index.js
