name: 'Update repository variable'
description: 'List the task deployed in an environment'
author: ''

inputs:
  token:
    description: 'Github token'
    required: true
    default: ''
  repository:
    description: 'Current repository'
    required: true
    default: ''
  environment:
    description: 'DXP environment'
    default: 'INTEGRATION'
  new-value:
    description: ''
    required: true
    default: ''
  prefix:
    description: ''
    default: ''
  variable-name: 
    description: ''
    default: ''

outputs:
  json-value:
    description: 'Commit logs'
  latest-commit-id:
    description: 'Latest commit hash'

runs:
  using: node20
  main: dist/index.js
