name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  commit-hash:
    description: 'Your input description here'
    required: true
    default: 'HEAD'

# Define your outputs here.
outputs:
  js-value:
    description: 'Your output description here'

runs:
  using: node20
  main: ./../dist/deployed-task-log/index.js
