name: 'List deployed task action'
description: 'List the task deployed in an environment'
author: ''

inputs:
  commit-hash:
    description: 'Commit id to start'
    required: true
    default: 'HEAD'
  repository:
    description: 'Current repository'
    required: true
    default: ''

outputs:
  json-value:
    description: 'Commit logs'
  latest-commit-id:
    description: 'Latest commit hash'

runs:
  using: node20
  main: dist/index.js
