name: Setup semantic release action
description: 'Setup semantic release action'

inputs: 
  token: 
    description: 'Github Token'
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        curl -H "Authorization: token ${{ inputs.token }}" https://raw.githubusercontent.com/john-christian-melendres/GHCustomActions/main/semantic-release/package.json
      shell: bash
  
    - run: |
        curl -H "Authorization: token ${{ inputs.token }}" https://raw.githubusercontent.com/john-christian-melendres/GHCustomActions/main/semantic-release/release.config.js
      shell: bash

    - run: |
        ls
      shell: bash
  
    - name : Install Dependencies
      run: npm i
      shell: bash

    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash

    